// Generated by tools/derive-accents.mjs. Do not edit by hand.
//
// Each accent keeps the hue Vice shipped and moves to the tonal position the
// neutral theme uses for dark mode, so it sits correctly on the #1b1b1b body
// instead of on the old near-black void. Every value clears WCAG AA against
// the body, the raised surface, and its own on-accent text colour.

export type AccentName = 'blue' | 'purple' | 'green' | 'red' | 'orange';

export interface AccentRamp {
  /** Fills, focus rings, the record indicator. Carries dark on-accent text. */
  base: string;
  hover: string;
  active: string;
  /** Drives the ambient background wash. Never used for text. */
  ambient: string;
  /** Raised surfaces: cards, tiles, panels. Flat, with a trace of the hue. */
  surface: string;
  surfaceHover: string;
}

export const ACCENTS: Record<AccentName, AccentRamp> = {
  blue: {
    base: '#45a7fe',
    hover: '#73baff',
    active: '#2b91e6',
    ambient: '#072f51',
    surface: '#21262b',
    surfaceHover: '#2b323a',
  },
  purple: {
    base: '#a68aff',
    hover: '#b7a4ff',
    active: '#9370f1',
    ambient: '#302550',
    surface: '#25242b',
    surfaceHover: '#32303a',
  },
  green: {
    base: '#46ba8a',
    hover: '#5ccd9c',
    active: '#29a475',
    ambient: '#003824',
    surface: '#202723',
    surfaceHover: '#2a342f',
  },
  red: {
    base: '#fc6d66',
    hover: '#ff9087',
    active: '#e35652',
    ambient: '#4d1c1a',
    surface: '#2b2322',
    surfaceHover: '#3a2e2d',
  },
  orange: {
    base: '#ef7e3e',
    hover: '#ff945c',
    active: '#d76824',
    ambient: '#4b2005',
    surface: '#2a2420',
    surfaceHover: '#392f2a',
  },
};

export const DEFAULT_ACCENT: AccentName = 'blue';

export const ACCENT_NAMES = Object.keys(ACCENTS) as AccentName[];
