// Generated by tools/derive-accents.mjs. Do not edit by hand.
//
// Each accent keeps the hue Vice shipped and moves to the tonal position the
// neutral theme uses for dark mode, so it sits correctly on the #1b1b1b body
// instead of on the old near-black void. Every value clears WCAG AA against
// the body, the raised surface, and its own on-accent text colour.

export type AccentName = 'blue' | 'purple' | 'green' | 'red' | 'orange';

export interface AccentRamp {
  /** Fills, focus rings, the record indicator. Carries dark on-accent text. */
  base: string;
  hover: string;
  active: string;
  /** Drives the ambient background wash. Never used for text. */
  ambient: string;
  /** The page background: a neighbouring hue to the accent, never black. */
  bg: string;
  /** Resting fill for cards, tiles and panels. The gray these replaced. */
  soft: string;
  /** A control at rest sitting on a soft surface: quiet buttons, inputs. */
  softRaised: string;
  /** Where a soft surface or a soft control goes under the pointer. */
  softHover: string;
}

export const ACCENTS: Record<AccentName, AccentRamp> = {
  blue: {
    base: '#45a7fe',
    hover: '#73baff',
    active: '#2b91e6',
    ambient: '#072f51',
    bg: '#15171f',
    soft: '#222532',
    softRaised: '#2d3140',
    softHover: '#363b4d',
  },
  purple: {
    base: '#a68aff',
    hover: '#b7a4ff',
    active: '#9370f1',
    ambient: '#302550',
    bg: '#1a151c',
    soft: '#2b232e',
    softRaised: '#382d3b',
    softHover: '#433747',
  },
  green: {
    base: '#46ba8a',
    hover: '#5ccd9c',
    active: '#29a475',
    ambient: '#003824',
    bg: '#0f1a18',
    soft: '#182a28',
    softRaised: '#213634',
    softHover: '#28413f',
  },
  red: {
    base: '#fc6d66',
    hover: '#ff9087',
    active: '#e35652',
    ambient: '#4d1c1a',
    bg: '#1d1511',
    soft: '#30231c',
    softRaised: '#3d2e25',
    softHover: '#4a372d',
  },
  orange: {
    base: '#ef7e3e',
    hover: '#ff945c',
    active: '#d76824',
    ambient: '#4b2005',
    bg: '#1c160f',
    soft: '#2e2419',
    softRaised: '#3a2f22',
    softHover: '#463929',
  },
};

export const DEFAULT_ACCENT: AccentName = 'blue';

export const ACCENT_NAMES = Object.keys(ACCENTS) as AccentName[];
